### ISSUE TITLE
npm i fails

### ISSUE THREAD

**Issue by eyalc900** [AmbireTech/wallet#14]
trying to run `npm i` 
got this error:

```
npm ERR! path /Users/eyal/aa/ambire-wallet/node_modules/ganache-core/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@20.11.1 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp ERR! UNCAUGHT EXCEPTION
npm ERR! gyp ERR! stack TypeError: Cannot assign to read only property 'cflags' of object '#<Object>'
npm ERR! gyp ERR! stack     at createConfigFile (/Users/eyal/aa/ambire-wallet/node_modules/node-gyp/lib/configure.js:117:21)
npm ERR! gyp ERR! stack     at /Users/eyal/aa/ambire-wallet/node_modules/node-gyp/lib/configure.js:84:9
npm ERR! gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:191:23)
npm ERR! gyp ERR! System Darwin 23.6.0
npm ERR! gyp ERR! command "/Users/eyal/.nvm/versions/node/v20.11.1/bin/node" "/Users/eyal/aa/ambire-wallet/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/eyal/aa/ambire-wallet/node_modules/ganache-core/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v20.11.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! Node-gyp failed to build your package.
npm ERR! gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
```

**Comment by Ivshti** [comment]
check this out, not an ambire issue https://github.com/nodejs/node-gyp/issues/2752
